name: CI

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository)
    steps:
    - name: Install dependencies
      run: |
        sudo pip install pipenv
        
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install python environment
      run: pipenv install --dev 

    - name: Run CI
      env:
        PYTHONPATH: src/main/python
      run: /bin/sh scripts/ci.sh
